import json
from pprint import pprint

with open('Youtube_Example.json') as data_file:
    data = json.load(data_file)

print("apiVerion[0] = " + data["apiVersion"])

for item in data["data"]:
    print ("data[0].updated = " + item["updated"])
    print ("data[0].totalItems = " + item["totalItems"])
    print ("data[0].startIndex = " + item["startIndex"])
    print ("data[0].itemsPerPage = " + item["itemsPerPage"])
    print ("data[0].totalItems = " + item["totalItems"])
    print ("data[0].items[0].id = " + item["items"][0]["id"])
    print ("data[0].items[0].uploaded = " + item["items"][0]["uploaded"])
    print ("data[0].items[0].updated = " + item["items"][0]["updated"])
    print ("data[0].items[0].uploader = " + item["items"][0]["uploader"])
    print ("data[0].items[0].category = " + item["items"][0]["category"])
    print ("data[0].items[0].title = " + item["items"][0]["title"])
    print ("data[0].items[0].description = " + item["items"][0]["description"])
    print ("data[0].items[0].tags = " + item["items"][0]["tags"][0])
    print ("data[0].items[0].tags = " + item["items"][0]["tags"][1])
    print ("data[0].items[0].tags = " + item["items"][0]["tags"][2])
    print ("data[0].items[0].thumbnail.default = " + item["items"][0]["thumbnail"]["default"])
    print ("data[0].items[0].thumbnail.hqDefault = " + item["items"][0]["thumbnail"]["hqDefault"])
    print ("data[0].items[0].player.default = " + item["items"][0]["player"]["default"])
    print ("data[0].items[0].content.1 = " + item["items"][0]["content"]["1"])
    print ("data[0].items[0].content.5 = " + item["items"][0]["content"]["5"])
    print ("data[0].items[0].content.6 = " + item["items"][0]["content"]["6"])
    print ("data[0].items[0].duration = " + item["items"][0]["duration"])
    print ("data[0].items[0].aspectRatio = " + item["items"][0]["aspectRatio"])
    print ("data[0].items[0].rating = " + item["items"][0]["rating"])
    print ("data[0].items[0].ratingCount = " + item["items"][0]["ratingCount"])
    print ("data[0].items[0].viewCount = " + item["items"][0]["viewCount"])
    print ("data[0].items[0].favoriteCount = " + item["items"][0]["favoriteCount"])
    print ("data[0].items[0].commentCount = " + item["items"][0]["commentCount"])
    print ("data[0].items[0].status.value = " + item["items"][0]["status"]["value"])
    print ("data[0].items[0].status.reason = " + item["items"][0]["status"]["reason"])
    print ("data[0].items[0].accessControl.syndicate = " + item["items"][0]["accessControl"]["syndicate"])
    print ("data[0].items[0].accessControl.commentVote = " + item["items"][0]["accessControl"]["commentVote"])
    print ("data[0].items[0].accessControl.rate = " + item["items"][0]["accessControl"]["rate"])
    print ("data[0].items[0].accessControl.list = " + item["items"][0]["accessControl"]["list"])
    print ("data[0].items[0].accessControl.comment = " + item["items"][0]["accessControl"]["comment"])
    print ("data[0].items[0].accessControl.embed = " + item["items"][0]["accessControl"]["embed"])
    print ("data[0].items[0].accessControl.videoRespond = " + item["items"][0]["accessControl"]["videoRespond"])
